### ISSUE TITLE
Filter keywords

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#101]
Being able to filter out posts or comments mentioning particular keywords

**Comment by ShadowJonathan** [comment]
Optionally, also with regex, but thats a super-power-user feature.

**Comment by buresdv** [comment]
I'm afraid that using REGEX will absolutely destroy the battery life

**Comment by buresdv** [comment]
Also, does this include checking just the title, or does this proposal also include checking the body of the post? I see that as another battery killer if it includes checking the body
