### ISSUE TITLE
Comments are not scaling with DynamicType

### ISSUE THREAD

**Issue by WestonHanners** [mormaer/Mlem#103]
**Describe the bug**
When adjusting font size, the comment body text is not changing.

**To Reproduce**
View a comment thread and adjust font size

**Mlem Information:**
0.0.6 (22)

**Additional Context**
in Comment Item.swift around line 185 using `.dynamicTypeSize(.small)` locks the font to a specific size. replace this with a dynamic font.

**Comment by EricBAndrews** [comment]
On it--I'll have it ready to go by the time Post Overhaul goes through.

**Comment by WestonHanners** [comment]
@EricBAndrews did you take this up?

**Comment by EricBAndrews** [comment]
Yep, I've got the fix developed on my fork and it'll be included in my next PR

**Comment by EricBAndrews** [comment]
Resolved in #204
