### ISSUE TITLE
* App sometimes crashes when up-/downvoting posts/comments

### ISSUE THREAD

**Issue by meisterlix** [mormaer/Mlem#113]
**Describe the bug**
Sometimes the app crashes on up-/downvote. Does not always happen.

**Expected Behavior**
Throw some kind of exception if something didn't work.

**Actual Behavior**
Hard crash back to iOS Homescreen

**To Reproduce**
Up- or downvote some posts/comments in a row, preferably in quick succession.

**Mlem Information:**
0.0.6(22)
**Additional Context**
Used instance: sh.itjust.works

**Comment by buresdv** [comment]
Thanks for the report, this may be fixed by #52 since this seems like my shoddy handling of errors in the old implementation. We should check for this bug once the API client is done.
