### ISSUE TITLE
Add community's instance in the sidebar

### ISSUE THREAD

**Issue by Bo-Duke** [mormaer/Mlem#132]
## Introduction
Currently, there's no way from a community's page to see on which instance we are. This is troublesome for communities with the same name across instances (196 or technology for example)

![image](https://github.com/buresdv/Mlem/assets/9383709/cd39967e-eb2a-4baa-a3dc-4ca39674f451)
![image](https://github.com/buresdv/Mlem/assets/9383709/e04dfa36-da1a-4330-97e5-7434ed9b93c9)

The only way I found to know was to share the community and look at the URL in iOS' share sheet.

![image](https://github.com/buresdv/Mlem/assets/9383709/9f5e1054-feb4-4d64-870d-c3d6a7d02e59)

## Requirements
A way to easily see the full community name (with the `@instance`). The top of the sidebars bellow the users stats or in place of the "sidebar" text seems like a good place.

![image](https://github.com/buresdv/Mlem/assets/9383709/6f025b9f-94e2-452e-b769-ba72c2a5fc89)

## Title

Seems like communities can have titles too, like you can see on my share sheet screenshot. It might be a good idea to also add it to the sidebar as it might add context

**Comment by ShadowJonathan** [comment]
cc #79 and @buresdv

**Comment by ShadowJonathan** [comment]
Done by https://github.com/mormaer/Mlem/pull/218
