### ISSUE TITLE
* Certain posts lack a share option

### ISSUE THREAD

**Issue by porkins** [mormaer/Mlem#138]
**Describe the bug**
Certain posts, such as stickied text posts, like the Lemmy.world starting guide, lack a share button. 

**Expected Behavior**
All posts and comments should have a share button allowing for a permalink to be shared or copied. 

**Actual Behavior**
The reason this is a bug is because non-stickied text posts do have share buttons whereas stickied don’t. 

**To Reproduce**
In Lemmy.world go to lemmyworld and reviews the stickied text post. Note that it does not have a share icon.

**Comment by noloman** [comment]
I've already checked out the code and some of the posts indeed don't have the URL parameter (I still need to fully confirm that this only happens for sticky posts but I don't think so).
I realised that all posts have an `ap_id` parameter that is a URL.
What if I use it for the sharing feature if the URL parameter is nil?

If you all agree please assign this to me and I'll create the PR (I've already got the code).
