### ISSUE TITLE
More compact posts view

### ISSUE THREAD

**Issue by mkardi** [mormaer/Mlem#14]
It would be great to have more condensed view of submissions with only title visible.
Something like apollo has implemented.

![image](https://github.com/buresdv/Mlem/assets/81050091/cb5c503d-b895-4494-95cc-6566be6e2369)

**Comment by buresdv** [comment]
On it!

**Comment by buresdv** [comment]
This is a bit problematic due to the reuse of `Post Item.swift` in an expanded post, so I'll have to rewrite `Post Item.swift` almost entirely to make this customization possible.

I'm moving this to "Paused" for now, as there's a more pressing problem, #8

**Comment by buresdv** [comment]
Related to #38

**Comment by buresdv** [comment]
@EricBAndrews sorry for the ping, I'm trying to get you assigned to this issue. Please ignore ✌️

**Comment by EricBAndrews** [comment]
I'll roll this into my post enhancements

**Comment by EricBAndrews** [comment]
Resolved in #133
