### ISSUE TITLE
Comment Reply is only triggered when tapping the icon, not the text

### ISSUE THREAD

**Issue by MichaelOrmonde** [mormaer/Mlem#155]
**Describe the bug**
The tap interaction on the "reply" button to comments is only triggered by tapping the arrow icon, and not the word "reply" itself

**Expected Behavior**
User taps "reply" and reply UI appears; user can reply to the comment

**Actual Behavior**
Nothing happens

**To Reproduce**
* Open any post
* try to reply to a comment by pressing the word "Reply"

**Mlem Information:**
0.0.6(22)

**Additional Context**
Looks like this is fixed by moving the Text view inside the button at https://github.com/buresdv/Mlem/blob/ea6d321e96f6332e3681cda1425264a30f644d3b/Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment%20Item.swift#L98L110

**Comment by EricBAndrews** [comment]
UI has been completely overhauled.
