### ISSUE TITLE
Add swiftformat linter

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#157]
> On a related note, I was planning to bring [swiftformat](https://github.com/nicklockwood/SwiftFormat) into the project when I get a moment, likely set up as a pre-commit hook, what are your thoughts?
> 
> The thinking is it'll ensure the project is formatted to the _"official"_ language style, and saves any style based stuff creeping into reviews?

_Originally posted by @mormaer in https://github.com/buresdv/Mlem/pull/145#discussion_r1229878829_

**Comment by EricBAndrews** [comment]
Closed with #304
