### ISSUE TITLE
A post containing a youtube video link disappears when it has completely scrolled into view

### ISSUE THREAD

**Issue by krims0n32** [mormaer/Mlem#158]
**Describe the bug**
Scroll through feed. Regular posts show up fine. A post with a youtube link in it appears, but as soon as the post is in-view completely, it disappears, showing an empty space.

**Expected Behavior**
I expect the post containing the youtube link not to disappear.

**Actual Behavior**
The post disappeared.

**To Reproduce**
Scroll through both regular content and content containing a youtube link.

**Mlem Information:**
0.0.6 (22)

**Additional Context**
See screenshots.

![image](https://github.com/buresdv/Mlem/assets/661853/2c2e7bca-17de-4b90-96db-de280dd4a0fd)
![image](https://github.com/buresdv/Mlem/assets/661853/4032dce6-abe4-45d1-a4f2-14ccdaf9cb5c)

**Comment by buresdv** [comment]
Can confirm, this still happens in the latest release

**Comment by EricBAndrews** [comment]
Cannot replicate in latest release.
