### ISSUE TITLE
Images that are too large create an intersected link view

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#167]
![image](https://github.com/buresdv/Mlem/assets/22740616/c88fb809-9c99-44fd-9246-af347c9bb183)

https://lemmy.blahaj.zone/post/121406

**Comment by Emiliaaah** [comment]
I have a feeling the issue I ran into has to do with this one, but I could be mistaken.

I can open the comments for [this post](https://lemmy.world/post/602364):
https://github.com/mormaer/Mlem/assets/55017867/bc48728f-f8d1-4259-aaed-f11cfe4c5308

**Comment by JakeShirley** [comment]
Fix in PR!

https://github.com/mormaer/Mlem/pull/374
