### ISSUE TITLE
Publish to the App Store

### ISSUE THREAD

**Issue by lazzurs** [mormaer/Mlem#172]
## Introduction
It would be great to see the app in the App Store so more users could use the app.

## Requirements
Publish the App to the Apple App Store and have regular releases go there.

## Discussion
Since Lemmy is getting more and more popular an iOS client is a clear need for the community and not being able to get the app from the App Store is going to be a blocker for most users.

If there is a reason the app has not been published yet it would be good to discuss that in this issue so users can be aware of this. I had a look through the issue history but could not find any discussion of this.

**Comment by ShadowJonathan** [comment]
We have a tentative plan to release to the App Store on July 1st, but that can be subject to change, if we're not satisfied with the quality of the app we have then.

**Comment by lazzurs** [comment]
Any good first issues to jump on that need to be solved before publishing?

**Comment by ShadowJonathan** [comment]
There's a lot, but we also have a bunch of people working on it, and to prevent a too-many-cooks scenario, we're dialing down adding new people to the process, because of this, sorry.

**Comment by anlumo** [comment]
The Testflight beta program is full right now.

**Comment by Write** [comment]
Could you add more Testflight Slot in the mean time ? thanks a bunch .

**Comment by buresdv** [comment]
> Could you add more Testflight Slot in the mean time ?

Unfortunately not, we have reached the hard user limit

**Comment by EricBAndrews** [comment]
This isn't an issue
