### ISSUE TITLE
Fix: Update README as TestFlight link is now broken due to ownership change.

### ISSUE THREAD

**Issue by acdoe98** [mormaer/Mlem#219]
Once the application has been submitted by the new org on TestFlight, just a reminder to update the TestFlight badge in the README of this repository. 

Kudos, for the work on Mlem so far, it’s been a pleasure to use, test, and watch grow. Can’t wait to test the next builds as they drop!

**Comment by localjo** [comment]
Can someone comment the new link in this thread?

**Comment by WestonHanners** [comment]
Should have a new link later tonight. Working out some kinks in our CD system.

**Comment by MrAusnadian** [comment]
@WestonHanners any update on this? I'm able to assist if needed, I've worked on TestFlight setup/config pretty extensively in the past.

**Comment by WestonHanners** [comment]
We have our build in TestFlight review. Once the link is shared we can update this.

**Comment by MrAusnadian** [comment]
![brooklyn99-noice](https://github.com/mormaer/Mlem/assets/9650258/f3606f02-9c7a-4fe2-9f66-2d9a5334bb3e)

**Comment by daberkow** [comment]
I see a new test flight on lemmy, wanted to verify this is the legit one

**Comment by MrAusnadian** [comment]
PR for this: https://github.com/mormaer/Mlem/pull/257
