### ISSUE TITLE
Functional Features for v1.0

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#225]
This is a tracker/checkoff issue for features/UX flows that we want to get in to the app before we launch the first version of the app.

----

- [x] Settings Tab
- [x] Feed Tab
  - [x] Community List View (https://github.com/mormaer/Mlem/issues/78)
  - [x] Posts
  	- [x] Comments
  	- [x] Reply
  - [x] Sidebar (https://github.com/mormaer/Mlem/issues/132)
- [ ] Account
  - [ ] Basic Info
- [ ] Inbox (Partially https://github.com/mormaer/Mlem/issues/45)
  - [ ] Messages
  - [ ] Comments
  - [ ] Poll-based refresh

**Comment by JakeShirley** [comment]
Sidebar should be mostly done with #218

**Comment by EricBAndrews** [comment]
Moved this info to milestone
