### ISSUE TITLE
Bug when swiping

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#236]
On test build 0.0.7 (5)

https://github.com/mormaer/Mlem/assets/22740616/66b0564b-400a-4bfc-b3ab-a788dbbb90db

**Comment by EricBAndrews** [comment]
Resolved in latest release.

**Comment by ShadowJonathan** [comment]
Doesn't seem so; https://github.com/mormaer/Mlem/issues/297
