### ISSUE TITLE
Not all communities show up on the community list

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#242]
![image](https://github.com/mormaer/Mlem/assets/22740616/2194d8c3-c153-47c6-a45b-379e680e45ec)

![image](https://github.com/mormaer/Mlem/assets/22740616/fc113d09-247f-48ce-b5ce-e44c7136a559)

(In the second image I'm holding a scroll with one finger while also taking a screenshot)

0.0.7 (6)

**Comment by JakeShirley** [comment]
Fixed in #274 (when that merges)

**Comment by ShadowJonathan** [comment]
Ah, right, and it seems that this is also a general issue, since i'm seeing it on testflight.

I thought this was about this one numerical community, but it is just an arbitrary limited amount.

**Comment by JakeShirley** [comment]
Fixed in #274!
