### ISSUE TITLE
Cannot edit or delete comments after making them

### ISSUE THREAD

**Issue by Guy-Dudeman** [mormaer/Mlem#251]
## Introduction
When you click on the "..." menu, there is no option to edit or delete your comment.

## Requirements
Either add two buttons to before the "..." menu, or put an option inside the "..." menu to be able to edit or delete your comment.

## What I Need
The ability to edit or delete a comment.

**Comment by BrooklynMan** [comment]
yeah, this is an issue that needs attention soon

**Comment by EricBAndrews** [comment]
Captured in new issues
