### ISSUE TITLE
* post goes partly off-screen

### ISSUE THREAD

**Issue by Emiliaaah** [mormaer/Mlem#262]
**Describe the bug**
I came across this post on my feed https://lemmy.ml/post/1466711

**Expected Behavior**
I would expect the post to be entirely onscreen

**Actual Behavior**
A part of the post is not visible (you have to do some swipes magic to see part of the post).

https://github.com/mormaer/Mlem/assets/55017867/85a98e03-ebc8-4588-9c87-97f027703651

**To Reproduce**
You'd need this post to show up in your feed, or look for it in the piracy community (piracy@lemmy.dbzer0.com)

**Mlem Information:**
Version 0.1.0 (14)
I've only seen this happening on the new version but it could be that it's something unique to the post that caused this.

**Additional Context**
Any other relevant information

**Comment by Emiliaaah** [comment]
I also found the following post https://lemmy.ml/post/1444424

https://github.com/mormaer/Mlem/assets/55017867/ac9e8b91-6978-4dfb-a2fd-64c9ce5fbfca

**Comment by Emiliaaah** [comment]
And another one https://lemmy.dbzer0.com/post/35555

**Comment by EricBAndrews** [comment]
Bundling this with #291--we need to handle images within text posts

**Comment by EricBAndrews** [comment]
Child issue of #308

**Comment by EricBAndrews** [comment]
Closed in #336
