### ISSUE TITLE
* Posts with multiple images cause resizing issues

### ISSUE THREAD

**Issue by MarsAgainstVenus** [mormaer/Mlem#266]
**Describe the bug**
Scrolling through /c/all, a post with multiple images went from one image with a normal size to increasingly zoomed in images.

**Expected Behavior**
Each image should have been the same size as the first.

**Actual Behavior**
Images did not keep the correct size. 

**To Reproduce**
Scroll through @retrogaming@lemmy.world to this post: https://lemmy.world/post/518834 or any community with any post that contains more than one image.

**Mlem Information:**
0.1.0(14)

**Additional Context**
Any other relevant information

**Comment by EricBAndrews** [comment]
Child issue of #308

**Comment by EricBAndrews** [comment]
Closed in #336
