### ISSUE TITLE
New Feed sort options in API 0.18 need to be added to Mlem

### ISSUE THREAD

**Issue by BrooklynMan** [mormaer/Mlem#278]
Lemmy main feed now has additional sort options under Top:

- Top Hour
- Top Six Hours
- Top Twelve Hours

This a new 0.18 API addition, and should be added to Mlem's feed sort options

**Comment by ShadowJonathan** [comment]
IMO we shouldn't show these options to the user if the current server is not 0.18, if thats possible, though that'd add a lot of complexity in the code.

**Comment by EricBAndrews** [comment]
Closed in #279
