### ISSUE TITLE
Bookmark icon stands out too much

### ISSUE THREAD

**Issue by amadejpapez** [mormaer/Mlem#282]
## Introduction
Brief history

The Bookmark icon stands out and looks distracting. While glimpsing through the feed, I cannot ignore and not notice the Bookmark icon on screen because of its opposite color fill.

![image](https://github.com/mormaer/Mlem/assets/63184600/f4616778-167e-43e6-889f-92caa3201e3b)

![image](https://github.com/mormaer/Mlem/assets/63184600/69965d92-4b23-4d91-92f4-92c8b164fddf)

## Requirements
What needs to be done?

Perhaps change it to just an outline.

## Discussion
Go more in depth about the proposal

Some may also understand this fill as the post being bookmarked already. Some apps use outline before selection and after selection it becomes filled in.

## What I Need
What I need it to do

Look more like other buttons and not stand out. Share button alongside is also just an outline.

Thank you :)

**Comment by BrooklynMan** [comment]
change icon from `bookmark.fill` to `bookmark`

**Comment by amadejpapez** [comment]
> change icon from `bookmark.fill` to `bookmark`

Will try to submit a PR then. Hoping that's it, as I don't have a Mac to test this with. Thank you :D
