### ISSUE TITLE
* YouTube link is not opened

### ISSUE THREAD

**Issue by dotemacs** [mormaer/Mlem#283]
**Describe the bug**
Go to this post:
https://lemmy.world/post/279704

**Expected Behavior**
The link to the YouTube video to be tapped & opened

**Actual Behavior**
The link can’t be tapped & opened

**To Reproduce**
Visit that Lemmy post, in Mlem.
Try to tap the title of it.
Nothing happens.

**Mlem Information:**

version 0.1.0 (14)

**Additional Context**

n/a

**Comment by dotemacs** [comment]
The same for the Instagram link:

https://lemmy.world/post/184883

**Comment by EricBAndrews** [comment]
Fixed in #272
