### ISSUE TITLE
Need an invite for iOS TestFlight

### ISSUE THREAD

**Issue by EmanuelFaria** [mormaer/Mlem#284]
Found your app here: https://join-lemmy.org/apps

Clicked the apple icon hoping to download but was instead told there's a problem with the public link URL, and asked for an invite code for TestFlight. Happy to beta test if you'll DM the link/code to me.

Thanks and good luck!

![image](https://github.com/mormaer/Mlem/assets/9612595/70dceafd-792b-4202-85f0-98c3d7d3bea5)

![image](https://github.com/mormaer/Mlem/assets/9612595/fd6f579a-0918-415f-9420-6241d27b175e)

![image](https://github.com/mormaer/Mlem/assets/9612595/3bc4efa0-f2f4-4620-a9af-b250ef3f74ca)

**Comment by turnipjs** [comment]
That should definitely get fixed but for now you can use the button at the top of the README for this repo. It worked for me today.

**Comment by JakeShirley** [comment]
Sent in a PR here.  Thanks for letting us know about the dead link!

https://github.com/LemmyNet/joinlemmy-site/pull/201

**Comment by JakeShirley** [comment]
If it wasn't obvious, here is the new TestFlight link:

https://testflight.apple.com/join/MelFP11Y
