### ISSUE TITLE
Replace navigation with NavigationStack

### ISSUE THREAD

**Issue by buresdv** [mormaer/Mlem#29]
As the old `NavigationView` is deprecated in iOS 16, it should be migrated to use the new `NavigationStack` API.

Ideally, the NavigationStack would make use of a path so arbitrary screens can be pushed onto the stack (like the sidebar, which at the moment uses the old `isActive` method of pushing it to the stack).

## Discussion
There are some challenges, namely
- The need to use the `path:` property on `NavigationStack`, so there needs to be an implementation for a tracker that will store the path and modify it. The path needs to be set so that we can push `CommunitySidebarView` onto the stack when the user clicks on the "Sidebar" button in me menu.
- #30 could be related to the old implementation of `NavigationView`. Maybe converting to `NAaigationStack` would fix it.

**Comment by buresdv** [comment]
Done in a fast way by replacing `NavigationView` definition with `NavigationStack`. Nevertheless, that fixed #30.

Implement a more detailed implementation later

**Comment by tht7** [comment]
Stale! navigation was replaced and simplified already
