### ISSUE TITLE
Embeds and/or post link handling seems to be broken

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#292]
TFF came back with a comment about a Youtube video link that isn't showing in the app.

Going through and testing some different configurations, I realise that *none* of these show up in the app as a link to be clicked on;

<img width="787" alt="image" src="https://github.com/mormaer/Mlem/assets/22740616/658b394b-1db4-42b6-af40-52882d597bd0">

![image](https://github.com/mormaer/Mlem/assets/22740616/75d8fb63-7de0-4faa-9479-db0705f5d895)

**Comment by EricBAndrews** [comment]
@ShadowJonathan is this still an issue? There was another issue (#271) with link posts that was closed (#272)
