### ISSUE TITLE
* Not all Subscribed Communities show the in the subscribed community list

### ISSUE THREAD

**Issue by adude007** [mormaer/Mlem#294]
**Describe the bug**
Subscribed to communities in app

**Expected Behavior**
Community to be listed in the app

**Actual Behavior**
Only listed in subscription list on a mobile/desktop browser

**To Reproduce**
Not sure was working ok for a while. 

**Mlem Information:**
0.1.0 (14)

**Comment by ShadowJonathan** [comment]
Duplicate of #242
