### ISSUE TITLE
Hide downvote buttons for communities with feature disabled

### ISSUE THREAD

**Issue by becausebirds** [mormaer/Mlem#32]
## Introduction
Some instances of Lemmy have downvotes disabled community-wide. Mlem should hide the downvote buttons when viewing the content in these communities.

## Requirements
Recognize if downvotes are hidden in a specific Lemmy instance and hide buttons appropriately.

## Discussion
An example of a community with disabled downvotes: [Beehaw.org](https://beehaw.org)

**Comment by ShadowJonathan** [comment]
(Dev) These are exposed under `GET /site`, which we could pull after https://github.com/buresdv/Mlem/issues/52 is complete

**Comment by mormaer** [comment]
@EricBAndrews - based on the chat earlier I'll take a look at this 👍
