### ISSUE TITLE
Link/article posts with large image previews can escape their card boundaries

### ISSUE THREAD

**Issue by JakeShirley** [mormaer/Mlem#322]
**Describe the bug**
See image

**Expected Behavior**
Images of articles are clipped correctly.

**Actual Behavior**
Images of articles can escape into the wilds of the post feed.

**To Reproduce**
![image](https://github.com/mormaer/Mlem/assets/1000311/46372a8b-b142-4c54-8a6d-563247a5b3ae)

**Mlem Information:**
0.1.0

**Additional Context**
n/a

**Comment by Emiliaaah** [comment]
Duplicate of #167

**Comment by JakeShirley** [comment]
Closing as dupe of #167
