### ISSUE TITLE
Update post and comment layout

### ISSUE THREAD

**Issue by EricBAndrews** [mormaer/Mlem#326]
Update post and comment layout to match Figma.

Required:
- Update post and comment layout to match Figma
- Move share button into context menu (it should NOT appear on the interaction bars)
- Make showing community for local users an optional toggle

Recommended:
- Squash UserProfileLabel up into UserProfileLink
- Give UserProfileLink a `compact` bool to handle multiple display styles

Avatar sizes are set in AppConstants.

An initial implementation of the community avatar can be found in Views/Shared/Community Link View

**Comment by BrooklynMan** [comment]
comments should have a similar layout to compact view, with username on top and no community tag

**Comment by BrooklynMan** [comment]
<img width="818" alt="Screenshot 2023-06-26 at 3 36 47 PM" src="https://github.com/mormaer/Mlem/assets/5836168/f768eb54-90ac-49f6-9ac1-247a2a269255">

**Comment by BrooklynMan** [comment]
![Image](https://github.com/mormaer/Mlem/assets/5836168/4b2f0f74-0482-4324-b319-8664cf7588b1)

**Comment by EricBAndrews** [comment]
Closed in #391
