### ISSUE TITLE
Generic Trackers

### ISSUE THREAD

**Issue by EricBAndrews** [mormaer/Mlem#345]
Create a generic feed tracker and feed loading system to cut down on code duplication.

Core functionality:

- [x] Conforms to `ObservableObject`, publishing an array of items and an `isLoading` bool
- [x] Offers a `loadNextPage` method that loads the next page
- [x] Offers a `refresh` method that resets its items--it should fetch them into a temp variable before setting the main array to that in order to not display an empty feed while refreshing or if failed
- [x] Offers an `update` method that allows replacing an item with an updated version of that item (used for interactions)
- [x] Offers a way to easily identify whether a given item is the 10th-from-last in its array (used for loading infinite feed; note that this needs to be able to work in threaded feeds, so if an item is 10th-from-last in the *SomeItem* array but 50th-from-last in the (*SomeItem* interlaced with *AnotherItem*) array, it can still identify it as 10th-from-last and load accordingly--done with `loadMarkId` for inbox)

**Comment by mormaer** [comment]
Implemented in #375
