### ISSUE TITLE
* Comment timestamps mirror the posts

### ISSUE THREAD

**Issue by ExperiBass** [mormaer/Mlem#348]
**Describe the bug**
i noticed it after i posted a new comment.

**Expected Behavior**
i expected the time in the top right corner to display "now" or "0s".

**Actual Behavior**
the comment inherited the parent posts time, and in fact all comments do.

**To Reproduce**
Find a post with comments.

**Mlem Information:**
V0.1.0 (19)
the issue goes back to (12), the earliest build on tf.

**Comment by EricBAndrews** [comment]
Duplicate #289

**Comment by ExperiBass** [comment]
derp, search failed me
