### ISSUE TITLE
Jump to next comment button

### ISSUE THREAD

**Issue by FernandoBarcia** [mormaer/Mlem#358]
## Introduction
The jump to next comment button it's a great way to navigate throw comments.

## Requirements
A floating button that, when touching it, makes the view go to the next comment. If you press it, makes the view go to the comment before.

## Discussion
It could be amazing that the button could be customized in position, size and color.

**Comment by BrooklynMan** [comment]
this might be an option for when using ios's accessibility tools/functions, but would otherwise clutter Mlem's standace interface with too many buttons.

**Comment by FernandoBarcia** [comment]
Well, maybe it could be better options to implement this idea, like double tap on a specific or empty area to jump to the next comment.

**Comment by BrooklynMan** [comment]
all of the interfaces is already active for an action (or is planned to be), so that's not really an option.

sorry, but I don't see how we could implement this function at this time.
