### ISSUE TITLE
Improve Post font styling for better readability while viewing the feed

### ISSUE THREAD

**Issue by dtackgrounded** [mormaer/Mlem#364]
## Introduction
Current build 0.1.0(19) font styling for posts make it difficult to read while quickly skimming the feed. 

## Requirements
Improve visual diversity by increasing the font size for the post_title and decrease white level(contrast) for the post body text (especially for dark mode).

## Discussion
The problem is especially noticeable when different text posts are adjacent to each other, making it appear that one post runs into another.

## What I Need
What I need it to do

**Comment by EricBAndrews** [comment]
Post styling update already pending
