### ISSUE TITLE
* Wide tables in posts are "squished"

### ISSUE THREAD

**Issue by dtackgrounded** [mormaer/Mlem#365]
**Describe the bug**
While viewing a post with a table, the layout prioritizes the fixed width of the device screen and not the content.

**Expected Behavior**
The layout should prioritize the content in the table and if necessary, allow the table to extend beyond the left/right edge of the device. Users should b able view the entire table by scrolling the table horizontally; like Apollo.

**Actual Behavior**
The table is fixed width to the device screen width and all the content is "squished" in minimum column widths.

**To Reproduce**
This is especially noticeable with sports box scores; see an example post: https://lemmy.world/post/727846

**Mlem Information:**
0.1.0(19)
If this started happening recently, write which version introduced the bug

**Additional Context**
see attached screenshot
![New Note](https://github.com/mormaer/Mlem/assets/867563/95fd1273-77a0-4757-a377-07293da991c0)

**Comment by BrooklynMan** [comment]
aha... i was concerned this might pop up...

@EricBAndrews can you take a look at this?

**Comment by EricBAndrews** [comment]
Child of #326

**Comment by EricBAndrews** [comment]
Closed in #391
