### ISSUE TITLE
In compact mode, footer elements in post and comment cards (vote buttons, etc) are too small

### ISSUE THREAD

**Issue by BrooklynMan** [mormaer/Mlem#373]
the footer elements (vote buttons, etc) on all post card types and comment cards should be the same size as the text content-- enabling compact mode ONLY changes the layout, not the size of interactive elements. the intent of compact mode it to use a more compact layout, not to make items smaller and more difficult to read/use.

**Comment by EricBAndrews** [comment]
Closed in #391
