### ISSUE TITLE
Navigating to community clears account / loses tabs

### ISSUE THREAD

**Issue by mormaer** [mormaer/Mlem#378]
**Describe the bug**
When navigating to communities in app after tapping a recognised link, the inbox and user tabs disappear.

**Expected Behavior**
The link to redirect to a native community view or browser and for the tabs to remain in place.

**Actual Behavior**
We navigate to a community but the inbox/user tabs disappear.

https://github.com/mormaer/Mlem/assets/5231793/07460292-67f3-4dcb-bf0b-1eb3d382d267

**To Reproduce**
- Log in and navigate into a feed
- Tap the navigation area to open search
- Search for `new community`
- Tap `newcommunities@lemmy.world`
- Tap on some of the links to communities in the feed

**Mlem Information:**
Seen in 0.1.0 (21) may have existed before

**Comment by tht7** [comment]
I think that was addressed with #414 as far as I tested I can't repro
