### ISSUE TITLE
Swipe-to-Vote Functionality for Posts

### ISSUE THREAD

**Issue by AlphaPro06** [mormaer/Mlem#59]
## Introduction
This proposal aims to streamline user interaction within Mlem, an iOS client for Lemmy, by introducing swipe-to-vote functionality for posts.

## Requirements
We propose a new feature:

**Swipe-to-Vote**: Users should be able to upvote or downvote a post by swiping right or left on it, respectively, similar to the functionality present in the Apollo app.

## Discussion
**Swipe-to-Vote**

Swipe-to-vote simplifies user interaction with posts. Swiping right on a post will upvote it, while swiping left will downvote it. This feature mirrors the intuitive swipe actions common in many contemporary apps, improving Mlem's usability and engagem

## What I Need
1. **Code Adjustments**: Implement swipe gesture recognizers for each post to handle the upvote (swipe right) and downvote (swipe left) actions.
2. **Testing**: Validate the feature’s functioning and verify it doesn't negatively affect app performance.
3. **User Feedback**: Collect and evaluate user feedback post-deployment to assess the feature's impact.
4. **Iterative Improvements**: Continually refine the feature based on user feedback and observed behavior.

**Comment by ShadowJonathan** [comment]
I think it should be mentioned that for full "Apollo compatibility", we'd have a way of customising these swipes and all in settings.

**Comment by EricBAndrews** [comment]
I'll roll this one into my big post enhancement PR

**Comment by BrooklynMan** [comment]
it should be mentioned that a competing project has already integrated this feature

**Comment by EricBAndrews** [comment]
Resolved in #204

**Comment by ShadowJonathan** [comment]
Relevant; https://github.com/mormaer/Mlem/issues/236

but yes, this functionality is implemented
