### ISSUE TITLE
Save Post Feature Integration

### ISSUE THREAD

**Issue by AlphaPro06** [mormaer/Mlem#60]
## Introduction
This proposal focuses on integrating a key functionality, the "Save Post" feature, from the Lemmy website into its iOS client, Mlem.

## Requirements
I propose the addition of:

Save Post Feature: Users should be able to save posts for later viewing, a functionality currently available on the Lemmy website.

## Discussion
**Save Post Feature**

The "Save Post" feature allows users to mark posts they find interesting and would like to revisit later. Implementing this feature within Mlem will enhance content accessibility and user experience, aligning the app more closely with the website's functionalities.

## What I Need
1. Code Adjustments: Add the "Save Post" option in the post options and synchronize it with the user's Lemmy account
2. Testing: Ensure the feature's seamless operation and check its impact on overall app performance.
3. User Feedback: Collect user feedback after deployment to assess the feature's usefulness and acceptance.
4. Iterative Improvements: Based on feedback, make necessary adjustments and improvements over time.

**Comment by buresdv** [comment]
Great idea, in the current mockups, the button is integrated. See here for the button being without background when a post is not saved, and with a background when it is: 
![iPhone 13 mini - 1Feed](https://github.com/buresdv/Mlem/assets/22037369/045a68dd-9922-4485-9f93-7bfb0dba7bd4)

This feature is constrained by #52, which, when integrated, will make this feature possible. @ShadowJonathan can ping us when he's made more progress on the task.

**Comment by EricBAndrews** [comment]
I'm going to get to work implementing the frontend functionality for this--I'll hook it up to a stub for now and connect it to the backend pending #52

**Comment by buresdv** [comment]
@EricBAndrews great, thank you! Just keep in mind the mock-up I posted earlier, as that the "official" design. While there will be an overhaul of the comment design, make sure it fits the design 👍

**Comment by buresdv** [comment]
@EricBAndrews updated design doc here: https://www.figma.com/file/6TcPi4DD653iWQMaW2drZS/Mlem-Post-View?type=design&node-id=0%3A1&t=yH2fImU62aohlhyk-1

**Comment by buresdv** [comment]
@EricBAndrews could you rebase on `main` before continuing working on this? The new API client just got merged and I don't want you to run into bad conflicts later and become frustrated

**Comment by EricBAndrews** [comment]
Implemented long ago.
