### ISSUE TITLE
Handle links to communities

### ISSUE THREAD

**Issue by buresdv** [mormaer/Mlem#71]
## Introduction
As it is now, when clicking a link to a community, the app crashes because it expects a link to a website

## Requirements
When clicking on link in the  `community@instance.com` or `instance.com/c/community` formats, instead of crashing, the app should open that community.

**Comment by ShadowJonathan** [comment]
On a wider scale, `/resolve_object` would help with this, resolving links (https://lemmy.ml/c/mlemapp) and identifiers (`!mlemapp@lemmy.ml`) to either a;
- User
- Post
- Comment
- Community

Which can then be handled further
