### ISSUE TITLE
Choose default feed and default sorting of posts

### ISSUE THREAD

**Issue by isametry** [mormaer/Mlem#77]
Right now, the default view when opening the app is the `Subscribed` feed with `Hot` sorting. But the user might want to configure both of these to default to something else (for instance the `All` feed with `Active` sorting).

This is already possible with comments, but not with the feed itself.

`Settings > General` feels like the intuitive place for these options (that's where the comment sort setting currently lives).

**Comment by Sjmarf** [comment]
When I open the app, I'm taken to the account selection screen. So there's no 'default' feed - I have to pick one from the options in the 'communities' menu. Maybe I'm missing something?

The default post sort sounds like a good idea though. I'll work on implementing it.
