### ISSUE TITLE
See Post / Comment history on a user (or own user)

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#84]
As in the title; Have a way to show own post history, or post history of an arbitrary user.

**Comment by PumpedSardines** [comment]
I was wondering if you needed any help on development. I could do this issue if you want, since i would really want this. I looked at the code and i understand what you're trying to do. I'm not the best at Swift UI though as i mainly do TypeScript React stuff!

**Comment by Sjmarf** [comment]
#269
