### ISSUE TITLE
* Comment feed jumps around when there a lot of comments loaded

### ISSUE THREAD

**Issue by buresdv** [mormaer/Mlem#99]
**Describe the bug**
When browsing a post with a lot of comments, the feed jumps around: https://streamable.com/ej1n9k

**Expected Behavior**
The feed doesn't jump around like that.

**Actual Behavior**
The feed jumps around like that

**To Reproduce**
Have a very long feed of comments open and try to scroll

**Comment by WestonHanners** [comment]
This seems to happen on the feed too, not just comments.
